### ISSUE TITLE
Scale Calculation

### ISSUE THREAD

**Issue by devagl** [tum-vision/tum_ardrone#11]
In the file DroneKalmanFilter.h, the function computeEstimator that calculates the optimal value for the scale has **sigma_PTAM squared** in the denominator (Line 56 ). However in both your papers and the thesis, the formula has a **sigma_PTAM inverse \* sigma_IMU**. If this is only a typo, it can have big errors in the actual scale calculation, yes?

**Comment by JakobEngel** [comment]
it's not a typo/bug, it's a feature :D - it's just kinda cryptic code:
the "spi" in 

> > return 0.5*((sII-sPP)+sqrt(tmp)) / (stdDevPTAM \* stdDevPTAM \* spi);
> > is the raw sum, i.e. spi = sum(x_i \* y_i) and NOT sPI = sigma_x \* sigma_y \* sum(x_i \* y_i) = s_xy from the paper.
> > cheers, jakob
