### ISSUE TITLE
tum_ardrone with downward camera

### ISSUE THREAD

**Issue by whatgit** [tum-vision/tum_ardrone#12]
Hello,

I'm working with the ARDrone 2.0 and I would like to know whether it's possible to configure tum_ardrone package to use with downward camera (Actually I did some modification on the drone and now the forward camera is looking down)

**Comment by whatgit** [comment]
I changed the rotation matrix in PTAMWrapper.cpp from droneToFrontNT to droneToBottom instead and the coordinate problem is solved but the scale from PTAM is not correct.

Is there any way to correct this ?

**Comment by tmagcaya** [comment]
Did you solve this issue? Would love to know how you fixed the scale estimation.
I think the problem was that when you rotated ptam, the ultrasound had 90 degree rot difference to PTAM.
