### ISSUE TITLE
Reviving tum_ardrone

### ISSUE THREAD

**Issue by lesire** [tum-vision/tum_ardrone#16]
Message to all tum_ardrone user/dev, and specially addressed to @JakobEngel @dgitz @Lolu28 @Horizon0156 @phuicy @ffurrer @jennyhasahat

tum_ardrone looks dead when you look at the project activity (commits, pull requests, ...). However, I have just had a look at the forks, and a lot of people are forking and updating this code. Several of us have updated the package to use catkin. Some of us have made some quite specific updates: I personally tried to use actionlib in place of the script language, others implemented publication of PCL data, odometry, multiple drone version, ...

Maybe its time to converge and have a unique repo, with maybe several maintainers, and some branches on it so that the project may look alive again!

What is your opinion on that and your view of maintaining tum_ardrone?
Is there somebody from tum-vision here that may transfer or add maintenance to more active devs?

**Comment by ffurrer** [comment]
I would be up for code reviews now and once I have a drone again, which will be quite soon, with testing and where help is needed.

**Comment by lesire** [comment]
ok, so you are the official maintainer of this repo?
what's the strategy with this package? there is no branch in it, so is it planned to merge everything into master, or do you plan to create e.g. hydro-devel or indigo-devel branches? what about contributions?

updating the doc, and including a part about contributing via pull requests, would be a good idea

I can help if you want (e.g., having a look at all contributions in forks about catkin support, and format a unique pull request)

**Comment by ffurrer** [comment]
No I'm not the maintainer, would just be there to help in case there is interest in that.

**Comment by JakobEngel** [comment]
Yep, I am here ;) - mainly because I got an email, as you mentioned me explicitly.
Unfortunately, as you noticed, I do not have the time to properly look after the project any more, which is a shame really (I'm just too busy with other stuff). 

Of course I'd very much appreciate it if you, or someone else can look after it & give you my support / transfer maintenance rights etc. Starting this thread seems like a good start, considering that, as you said, many forks seem to do the same modifications, in particular catkin-compatibility.

**Comment by lesire** [comment]
I am of course ready to help, and I can for instance review pull requests or try to organise a bit the repo. My only limitation is that I am not a ROS addict, and I am only using ROS as part of another ecosystem. Hence, I won't be able to track all ROS modifications, or to test the repo for, e.g., indigo until indigo is released on my system.
So I think a good idea could be to have a team of maintainer, among who an active ROS user.

Anyway, I can already propose the following improvements/roadmap:
1. create a hydro-devel branch in which we have to merge all commits/forks that are adding catkin support and fixing issues
2. encourage people to contribute by making pull requests instead of keeping their own fork
3. having a core maintainer team to decide on major improvements that will be done on alternative branches on the main repo

**Comment by rohanbhargava11** [comment]
I have been working on ROS for past three years. My lab recently bought an ardrone and we have been testing tum_ardrone on it for past two months. I am more than happy to help to revive the tum_ardrone package.

**Comment by KarolHausman** [comment]
Hi everyone,

I've been working with the tum_ardrone package for awhile and I have
experience with ROS too. I would be happy to help.

I think the idea of creating another catkin branch is great. I have at
least 2 forks where I contributed with different things so I could create a
pull request with that.
However, I am quite busy these days so it might take awhile...

Cheers,
Karol

**Comment by lesire** [comment]
@JakobEngel if you can add, at least me, to the repo maintainers, I can start by reviewing pull request #15 (which has catkin support) and create a hydro-devel branch for that

**Comment by JakobEngel** [comment]
sounds good! 
I have given you and Karol admin rights to the repository, and @rohanbhargava11 and @ffurrer write access. let me know if there is anything else :)
Cheers,
Jakob

**Comment by KarolHausman** [comment]
Thanks Jakob!

**Comment by dgitz** [comment]
My lab is actively working on extending the capabilities of the slam
package as well.  We are primarily using fuerte so it would be nice to not
lose the rosbuild functionality.

David Gitz
UIC EE Masters Student
618-560-4335 (c)

**Comment by lesire** [comment]
ok, so now I have rights, so tonight I will:
- create a branch 'fuerte-devel' to save the current status (compilation with rosbuild)
- create a branch 'groovy-devel' and look at the catkin-related potential contributions

afterwards (once catkin would be supported on groovy-devel), I propose to create a new 'hydro-devel' branch from it and try to merge other contributions

**Comment by lesire** [comment]
@JakobEngel you gave me rights on tum-vision/ardrone_autonomy, but not on tum-vision/tum_ardrone. Could you please update the rights ot the tum_ardrone admins?

**Comment by JakobEngel** [comment]
oops, sorry - done.
