### ISSUE TITLE
Update source

### ISSUE THREAD

**Issue by GreyCardinalRus** [tum-vision/tum_ardrone#2]
Hi
How connect with author ( @JakobEngel ?)  for double check my mods and post it for all?
Mods little -  errors with gcc 4.7 & groove...

**Comment by JakobEngel** [comment]
for example by writing me an email... or via pull request here :)

**Comment by GreyCardinalRus** [comment]
some changes

MAIN target -compile UBUNTU 12.04 & ROS GROOVE & GCC 4.7

other target - in My ArDrone 2.0 not get altitude and Vx/Vy

how send ?
zip all src dir  (search lines with GreyCardinalRus comment - about 10 changes )
or create diff? (first i nedd learn how do it... ;)

**Comment by GreyCardinalRus** [comment]
New info
Changes not little -i am update to newest and little modify thirdparty

Суббота,  5 января 2013, 9:20 -08:00 от JakobEngel notifications@github.com:

**Comment by sameerparekh** [comment]
Here's the best way to submit changes 

https://help.github.com/articles/using-pull-requests

**Comment by GreyCardinalRus** [comment]
please add

#include < unistd.h > //  for GCC 4.7

in "video_play_source.cc"

**Comment by lesire** [comment]
Fixed by fbeffba5cb68718b44b8a161eb31b35edbf0898f on master
