### ISSUE TITLE
How can I get an error message of my AR Drone?

### ISSUE THREAD

**Issue by eisoku9618** [tum-vision/tum_ardrone#33]
Hi,
I start to use an AR Drone with this tum_ardrone package.

When I use an iPhon app to fly my drone,
I can get an error message in red on the top part of the screen of my iPhone (for example, Ultrasound Emergency).

However, when I use this tum_ardrone package as follows, I can find the error message neither on the terminals nor on the tum_ardrone GUI.

``` bash
roslaunch tum_ardrone ardrone_driver.launch
roslaunch tum_ardrone tum_ardrone.launch
```

Is there any way to get an error message of my drone with this package?

**Comment by lesire** [comment]
Hi,
Which version of ROS are you using?

Anyway, the ardrone driver node is from 
https://github.com/AutonomyLab/ardrone_autonomy

You should have a look at it to see if such a data is available.
I think some of the tutorials (bottom of ardrone_autonomy doc) provides a simple window displaying the camera image + some status (ardrone state + battery level if I remember correctly).

Maybe some pointer to ArdroneAutonomy is missing in the tum_ardrone doc...

**Comment by eisoku9618** [comment]
Thank you for your reply. I'll check the ardrone_autonomy.
(I'm using hydro with catkin)
