### ISSUE TITLE
Hovering Drift

### ISSUE THREAD

**Issue by oscarmendezm** [tum-vision/tum_ardrone#34]
Hi,

First, thank you for this package. I have been following some of the UAV work from TUM and I must say its pretty impressive. 

 I've been following this project for a while now, but it seems that everytime I get it running on my AR Drone the hovering simply doesn't work. My drone ends up wandering around the area its supposed to be hovering until it eventually crashes. 

I have good features at about 3m from the drone. I've modified to Kalmann Filter parameters as best I could. I've been playing around with the aggressiveness and the PID parameters, but I still can't seem to get it to hover in place.

Is there anything I'm missing? Am I doing something wrong? Do you have any recommendations for the setup I should have (features, space, etc). Finally, would it be possible to get a slightly more detailed calibration procedure?

I know its a lot of questions, but I am hoping to use this for a research project to control several UAVs. 

Thank you for your time!

Oscar

**Comment by atomoclast** [comment]
Did you resolve this? I just started to play with this ROS package, and my drone is drifting badly. Even when I try and get it to go to waypoints....have you found  a solution? I was looking up and seeing it may have to deal with the firmware version.
