### ISSUE TITLE
bug in DroneKalmanFilter.cpp

### ISSUE THREAD

**Issue by devagl** [tum-vision/tum_ardrone#4]
When adding a new PTAM Observation or a fake Observation, you check for the received time stamp against the variable 'predictedUpToTotal', a variable that doesn't seem to be updated ever after its initial declaration. Did you mean to check it against 'predictdUpToTimestamp' ?

**Comment by JakobEngel** [comment]
humm, sorry for the long delay, but you are right, thanks. 
ill fix that as soon as possible :)
